version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: fleet_mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}_root
    ports:
      - "3306:3306"
    volumes:
      - mysql_fleet_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fleet_fastapi_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
    env_file:
      - .env
    depends_on:
      - db

volumes:
  mysql_fleet_data: